language: node_js
node_js:
  - "7"

cache: yarn

before_deploy:
  - yarn build

deploy:
  provider: pages
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: develop
